name: javascript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Use Node.js LTS (18.x)
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381
        with:
          node-version: '18'
      - name: Install project development dependencies
        run: npm i
      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
